version: '2.4'
services:
  mpd:
    #build:
    #  context: ./
    #  dockerfile: debian.armhf.Dockerfile
    ##  dockerfile: alpine.armhf.Dockerfile
    image: tobi312/rpi-mpd:debian
    #image: tobi312/rpi-mpd:alpine
    #image: tobi312/rpi-mpd:alpine-nocap
    container_name: mpd
    ports:
      - 6600:6600
      - 8000:8000
    volumes:
      - ./music:/var/lib/mpd/music:rw
      - ./playlists:/var/lib/mpd/playlists:rw
      - ./data:/var/lib/mpd/data:rw
      #- ./mpd.conf:/etc/mpd.conf:rw
      ## Time:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/snd:/dev/snd"
    cap_add:
      - SYS_NICE
    restart: unless-stopped